spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/test_db
    username: postgres
    password: postgres
  main:
    web-application-type: reactive
  lifecycle:
    timeout-per-shutdown-phase: 30s

server:
  shutdown: graceful
